---
title: "Multas em São Paulo"
date: "2017-03-15T13:07:31+02:00"
tags: ["r", "dados-abertos"]
categories: ["r"]
banner: "img/banners/"
author: ["Daniel"]
draft: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

Há bastante tempo tenho vontade de fazer análises usando dados de multas de São Paulo. 
O problema é: estes dados estão disponíveis? Na teoria, sim. Os dados de multas, como
quantidade de multas por tipo de infração, dia e horário, e outros são divulgados no
[portal da Mobilidade Segura](http://mobilidadesegura.prefeitura.sp.gov.br/QvAJAXZfc/opendoc.htm?document=Painel_Mobilidade_Segura.qvw&host=QVS%40c65v27i&anonymous=true) da Prefeitura de São Paulo. Na prática, é um pouco
diferente. Apesar do site fornecer uma opção de exportação, a tabela 
exportada não é completa e muitas informações ficam faltando. Para exportar as tabelas
com todas informações da bastante trabalho.

Para não ter o trabalho de exportar tabela por tabela, fiz uma requisição para a
prefeitura, por meio da Lei de Acesso à Informação, pedindo acesso direto ao banco de 
dados que fornece as informações para o Portal. A resposta foi a seguinte:

> Prezado Senhor Daniel, Agradecemos o contato e informamos que o seu pedido foi indeferido com fundamento no art. 16, inciso III, do Decreto nº 53.623/2012, pois a base de dados contém informações pessoais que não podem ser disponibilizadas a terceiros. Os demais dados encontram-se inseridos no Painel Mobilidade Segura para consulta pelos interessados com a possibilidade de exportar arquivos. Informamos ainda que na época da sua solicitação, os painéis se encontravam atualizados, visto que a atualização mensal ocorre após os 70 dias da data da infração 

A resposta ao meu ver é totalmente contraditória: ao mesmo tempo que eu não posso 
receber os dados porque eles são confidenciais, eu posso obtê-los pelo site, que
"oferece possibilidade de exportação de arquivos". (???)

Antes mesmo de pedir acesso ao banco de dados tinha pensado em desenvolver um 
webscrapper para fazer o download automático das planilhas, mas a tecnologia com 
a qual o portal foi desenvolvido (QlikView) dificulta muito o desenvolviento.

Sobrou fazer o download manual mesmo. Até agora fiz o download de todos as planilhas
de 2014 a 2016 contendo infrações capturadas tanto eletrônica quanto manualmente 
de carros (ainda faltam ônibus, utilitários, etc.) por hora do dia. Isso quer dizer
que já temos planilhas suficientes para criar uma tabela:

* tipo de veículo (sempre seria carro)
* data (2014 a 2016)
* hora do dia
* eletronica/manual
* motivo da multa
* localizacao da multa (quando for um radar)
* quantidade de multas

Disponibilizei esses dados [neste repositório](https://github.com/dfalbel/spmultas)
do Github. 

Agora com as análises a seguir, espero criar curiosidade e interesse para que mais
pessoas possam ajudar no download completo dos dados. Na página inicial do 
repositório, adicionei, um mini-tutorial de como você pode ajudar fazendo os 
downloads.

Vamos às análises.



