---
title: "Quebrando CAPTCHAs - Parte V: Redes Neurais"
date: "2017-06-05T13:07:31+02:00"
tags: ["r", "captcha"]
categories: ["r"]
banner: "img/banners/keras.jpg"
author: ["Julio"]
draft: true
summary: "No último post sobre CAPTCHAs anunciei uma série de posts sobre CAPTCHAs. Uma da nossas iniciativas principais nesse tema é a criação do pacote decryptr, um framework completo para modelagem de CAPTCHAs. Hoje veremos como..."
---

Nesse post tentarei falar da parte teórica por trás dos modelos 

## Definição

## Sequence labelling

O objetivo da classificação sequencial é atribuir sequências de valores obtidos de um alfabeto finito. As aplicações mais comuns dessa área são classificação de áudio (*speech recognition*) e leitura de textos escritos à mão (usando imagens).

O nosso caso é muito similar com a leitura de textos escritos à mão, com a diferença de que os caracteres são independentes.

A tarefa de classificação sequencial se subdivide em três tipos:

1. Classificação de sequência: cada sequência tem uma categoria própria.
1. Classificação de segmentos: existe um número fixo de segmentos no *input* e cada segmento recebe uma classificação.
1. Classificação temporal: os segumentos do *input* não são fixos.

Nosso interesse reside em (2).

## Redes neurais

Dois tipos

- Feed-forward NN -> perceptron
- Recurrent NN

## Perceptron



### Exemplo

## Layers utilizados no modelo

### Dense layer

#### Ativação

### Redes convolucionais

### Redes de memória longa

### Bidirecional

## Otimização