---
title: "Contrastes no R: um guia de como domar e interpretar seus parâmetros"
date: "2017-05-22T21:12:00+03:00"
tags: ["r", "contrastes", "formula", "interpretação"]
categories: ["r"]
banner: "img/banners/contrastes.png"
author: ["Athos"]
draft: true
summary: "Na modelagem estatística, muitas vezes brigamos com os parâmetros em vez de compreendê-los. Nesse post iremos aprender a interpretá-los e a domá-los para usá-los em nosso benefício."
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, comment = FALSE,
                      eval=FALSE)
```

```{r, echo = F, message=FALSE, warning=FALSE, comment=FALSE}
library(tidyverse)
library(magrittr)
```

```{r, echo = FALSE, comment = FALSE, message = FALSE}
dataset <- read.csv2("2017-05-21-contrastes-em-r/canc3.csv")
```


## Exemplo: 

```{r}
n = 4
contr.helmert(n, contrasts = TRUE, sparse = FALSE)
contr.poly(n, scores = 1:n, contrasts = TRUE, sparse = FALSE)
contr.sum(n, contrasts = TRUE, sparse = FALSE)
contr.treatment(n, base = 1, contrasts = TRUE, sparse = FALSE)
contr.SAS(n, contrasts = TRUE, sparse = FALSE)


contr.helmert(n, contrasts = FALSE, sparse = FALSE)
contr.poly(n, scores = 1:n, contrasts = FALSE, sparse = FALSE)
contr.sum(n, contrasts = FALSE, sparse = FALSE)
contr.treatment(n, base = 1, contrasts = FALSE, sparse = FALSE)
contr.SAS(n, contrasts = FALSE, sparse = FALSE)
```



## Os tweaks
