---
title: "Lei de Benford"
date: "2017-04-20T13:07:31+02:00"
tags: ["erro", "r"]
categories: ["r"]
banner: "img/banners/error.jpg"
author: ["Julio"]
draft: true
summary: "Tratar erros no R é importante para identificar problemas nos códigos e evitar retrabalho. Quem nunca rodou um algoritmo pesadíssimo que deu errado na última iteração? Nesse artigo, veremos como trabalhar com erros no R e a versão tidy dessas soluções."
---

## Lei de Benford

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval=FALSE, cache = TRUE)
```

## Relatórios do Tesouro Nacional

## Coleta dos dados

```{r}
library(magrittr)
link_tesouro <- 'http://www.tesouro.fazenda.gov.br/-/relatorio-de-gestao-fiscal'
pagina <- httr::GET(link_tesouro)

links_pdf <- pagina %>% 
  httr::content('text') %>% 
  xml2::read_html() %>% 
  rvest::html_node('.artigo > table') %>% 
  rvest::html_nodes('a') %>% 
  rvest::html_attr('href') %>% 
  purrr::keep(~stringr::str_detect(.x, 'onsolid|\\.doc|Portaria'))

links_nomes <- links_pdf %>% 
  stringr::str_match('/([^/]+\\.pdf)') %>% 
  magrittr::extract(TRUE, 2)

dir.create('pdf', showWarnings = FALSE)
purrr::walk2(links_pdf, links_nomes, ~{
  url <- glue::glue('http://www.tesouro.fazenda.gov.br/{.x}')
  arq <- glue::glue('pdf/{.y}')
  httr::GET(url, httr::write_disk(arq, overwrite = TRUE))
})

```

```{r}
d_txt <- dir('pdf', full.names = TRUE) %>% 
  tibble::enframe('id', 'arq') %>% 
  dplyr::mutate(txt = purrr::map(arq, pdftools::pdf_text))

pegar_numeros <- function(txt) {
  txt %>% 
    unlist() %>% 
    # ([[:space:]+-]|^)
    stringr::str_extract_all('[0-9.,]+') %>% 
    purrr::flatten() %>% 
    stringr::str_trim() %>% 
    stringr::str_replace_all('[^0-9]', '') %>% 
    stringr::str_replace_all('^20[01][0-9]', '') %>% 
    stringr::str_replace_all('^0+', '') %>% 
    stringr::str_subset('^[0-9]')
}

pegar_digs <- function(numeros, digs = 2) {
  numeros %>% 
    stringr::str_sub(1L, digs) %>% 
    tibble::enframe('id', 'digito') %>% 
    dplyr::filter(stringr::str_length(digito) == digs) %>% 
    dplyr::select(-id)
}

d_val <- d_txt %>% 
  dplyr::mutate(numeros = purrr::map(txt, pegar_numeros)) %>% 
  dplyr::mutate(dig1 = purrr::map(numeros, pegar_digs)) %>% 
  dplyr::select(arq, dig1) %>% 
  tidyr::unnest(dig1)
```

## Resultados

```{r}
library(ggplot2)
dbenford <- function(x) {
  log10(1 + 1 / x)
}

p <- d_val %>% 
  dplyr::filter(digito != '21') %>% 
  dplyr::count(arq, digito) %>% 
  dplyr::mutate(prop = n / sum(n)) %>% 
  dplyr::ungroup() %>% 
  dplyr::mutate(digito = as.numeric(digito)) %>% 
  dplyr::mutate(nm = tools::file_path_sans_ext(basename(arq)),
                quadrimestre = stringr::str_extract(nm, '[1-3]Q'),
                ano = stringr::str_match(nm, '(20[01][0-9])([_xX+]|$)')[,2]) %>% 
  ggplot(aes(x = digito, y = prop, colour = quadrimestre)) +
  geom_line() +
  facet_wrap(~ano, scales = "free_y") +
  stat_function(fun = dbenford, colour = 'blue') +
  scale_x_continuous(breaks = 1:9 * 10) +
  scale_y_continuous(labels = scales::percent) +
  theme_bw(15)
p
```

```{r}
p2 <- d_val %>% 
  # dplyr::count(arq, digito) %>% 
  # dplyr::mutate(prop = n / sum(n)) %>% 
  # dplyr::ungroup() %>% 
  dplyr::mutate(digito = as.numeric(digito)) %>% 
  dplyr::mutate(nm = tools::file_path_sans_ext(basename(arq)),
                quadrimestre = stringr::str_extract(nm, '[1-3]Q'),
                ano = stringr::str_match(nm, '(20[01][0-9])([_xX]|$)')[,2]) %>% 
  ggplot(aes(x = digito)) +
  geom_histogram(aes(y = ..density..), bins = 10) +
  facet_wrap(~ano, scales = "free_y") +
  stat_function(fun = dbenford, colour = 'blue') +
  scale_y_continuous(labels = scales::percent) +
  theme_bw(15)
p2
```


```{r}
library(benford.analysis)
data(corporate.payment)
```

