---
title: "Teste htmlwidgets"
date: "2017-03-01T23:26:00+03:00"
tags: ["leaflet", "mapas", "r"]
categories: ["r"]
banner: "img/banners/markercluster.png"
author: ["Julio"]
draft: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

## plotly

```{r}
plotly::plot_ly(z = ~volcano, type = "surface")
```

## leaflet

```{r}
library(leaflet)
leaflet() %>% addTiles() %>%  setView(-93.65, 42.0285, zoom = 17)
```

## networkD3

```{r}
data(MisLinks, package = 'networkD3')
data(MisNodes, package = 'networkD3')
# Create graph
n <- networkD3::forceNetwork(Links = MisLinks, Nodes = MisNodes,
                        Source = "source", Target = "target",
                        Value = "value", NodeID = "name",
                        Group = "group", opacity = 0.4, zoom = TRUE)
n
```

## dygraphs

```{r}
library(dygraphs)
lungDeaths <- cbind(mdeaths, fdeaths)
dygraph(lungDeaths)
```

## DiagrammeR

```{r}
DiagrammeR::grViz("
  digraph boxes_and_circles {
  # a 'graph' statement
  graph [overlap = true, fontsize = 10]
  # several 'node' statements
  node [shape = box,
  fontname = Helvetica]
  A; B; C; D; E; F
  node [shape = circle,
  fixedsize = true,
  width = 0.9] // sets as circles
  1; 2; 3; 4; 5; 6; 7; 8
  # several 'edge' statements
  A->1 B->2 B->3 B->4 C->A
  1->D E->A 2->4 1->5 1->F
  E->6 4->6 5->7 6->7 3->8
  }
")

```

## DT

```{r}
d <- DT::datatable(mtcars)
d$dependencies[[2]] <- NULL
d
```
