---
title: "pesqEle: pacote para organizar e analisar pesquisas eleitorais"
date: "2018-04-25T00:00:00+00:00"
tags: ["musica"]
categories: ["análises", "r"]
banner: "img/banners/chorrrds.png"
author: ["Julio"]
summary: ""
draft: true
---

Além de ser sócio da [R6](rseis.com.br) consultoria, também estou presidente do [Conselho Regional de Estatística - 3a Região](http://conre3.org.br/portal). Uma de nossas incumbências como conselheiros é encontrar formas de monitorar e fiscalizar as pesquisas eleitorais.

Nesse ano eleitoral, por conta da pluralidade de candidatos e grande polarização política, a preocupação com as pesquisas eleitorais é ainda maior. O cenário incerto gera pesquisas com resultados incertos. Isso é um prato cheio para oportunistas que desejam influenciar a opinião pública através de pesquisas forjadas.

Por isso, é nossa obrigação como brasileiros acompanhar e monitorar as pesquisas eleitorais registradas, detectando e apontando o dedo para possíveis fraudes. Esse post busca resolver parcialmente esse problema.

# O sistema pesqEle

O [pesqEle]() é o repositório oficial de pesquisas eleitorais disponibilizado pelo Tribunal Superior Eleitoral (TSE).

# O pacote pesqEle

Infelizmente, o site do pesqEle não disponibiliza API para acesso aos dados. Por isso, foi necessário criar um raspador para obter os dados automaticamente. O pacote [`pesqEle`]() é o resultado desse esforço.

O pacote possui uma série de funções para download e arrumação dos dados do `pesqEle`. No final das contas, abstraímos tudo isso para disponibilizar tudo numa base de dados única, chamada `pesqEle`. 

```{r eval=FALSE}
glimpse(pesqEle::pesqEle)
```

Essa base contém todas as XXX pesquisas registradas no sistema até o dia 06/05/2018. As informações coletadas dessas pesquisas são:

-
-
-
-
-
-
-

A base passou por uma série de limpezas para ficar minimamente utilizável. Essas limpezas incluem arrumação de nomes dos estatísticos, empresas e municípios/UFs, 


### Atualização da base

A função `pesq_update()` recebe como input uma base de dados do pesqEle desatualizada e baixa as datas até hoje

## Arrumando os dados

Como em qualquer sistema público, os dados do pesqEle são bem desorganizados.

## Desenvolvendo o pesqEle

Se você tem interesse em baixar os dados de outras formas e aplicar outras regras para arrumação, você pode! No entanto, para isso terá de trabalhar com as funções não documentadas do `pesqEle`. O pacote está longe de seu estado atual.

Caso o pacote se torne realmente útil no futuro, pretendo deixar essas funções exportadas e documentadas. Para isso, no entanto, precisarei de muito apoio da comunidade.

Por enquanto, recomendo que você dê uma fuçada no [repositório do pacote no github](https://github.com/conre3/pesqEle) e adicione [issues](https://github.com/conre3/pesqEle/issues).

### Observaório das pesquisas eleitorais

