---
title: "Não use resultados de eleições para avaliar pesquisas eleitorais"
date: "2018-08-29T00:00:00+00:00"
tags: ["historia"]
categories: ["estatistica", "r"]
banner: "img/blog/desafio-recuperacao-img/purple_wave.jpg"
author: ["Julio"]
summary: "Será que a comparação de resultados de pesquisas eleitorais e resultados de eleições é correta? Nesse artigo, argumentarei que não e darei uma ideia de como as pesquisas eleitorais poderiam ser avaliadas na prática."
draft: false
---

A pesquisa eleitoral é a forma mais comum de conectar a população geral com conceitos básicos de estatística, como amostragem e inferência. Por isso, a descrença nas pesquisas eleitorais pode levar à descrença na estatística como um todo. Isso é prejudicial para nossos profissionais e, consequentemente, para a sociedade.

Uma discussão frequente em debates, redes sociais e conversas de bar é a validade de pesquisas eleitorais. No Brasil, existe uma sensação de descrença nas pesquisa, já que, historicamente, as pesquisas eleitorais erraram os resultados de eleições. 

Mas será que a comparação de resultados de pesquisas eleitorais e resultados de eleições é correta? Nesse artigo, argumentarei que não e darei uma ideia de como as pesquisas eleitorais poderiam ser avaliadas na prática.

## Pesquisas eleitorais: duas culturas

Leo Breiman, em seu [famoso artigo de 2001](http://www2.math.uu.se/~thulin/mm/breiman.pdf), discorre sobre a existência de duas culturas entre estatísticos: a voltada para **modelagem de dados** e a voltada para **modelagem algorítmica**. A primeira está interessada em compreender o mecanismo gerador dos dados observados, enquanto a segunda está interessada em predizer um conjunto de *outputs* a partir de um conjunto de *inputs*. 

Do ponto de vista matemático, essas culturas estão intimamente relacionadas e diferem somente com relação à função de perda que se quer minimizar [@Rizbicki, 2018]. Na prática, no entanto, isso gera muito atrito na comunidade científica e é o que está por trás da maior parte dos debates sobre *estatística vs machine learning*.

Curiosamente, o principal problema na interpretação de pequisas eleitorais está relacionado com as duas culturas. Considere as seguintes perguntas:

1. Se a eleição fosse hoje, qual seria a proporção de votos do candidato $A$?
1. Qual a probabilidade do candidado $A$ ganhar a eleição?

A principal afirmação desse artigo é a seguinte:

> Pesquisas eleitorais têm como objetivo responder (1), mas a sociedade as usa para responder (2).

Pesquisas eleitorais são levantamentos de intenção de voto. Seu objetivo é entender as opiniões da sociedade sobre dos candidatos, hoje. O objetivo não é predizer qual será o resultado da eleição.

Isso significa que utilizar resultados de eleições para avaliar a qualidade das pesquisas é uma comparação, no mínimo, injusta. É como avaliar a qualidade de um livro pela sua capacidade de servir como peso de papel.

## Pesquisas eleitorais podem ser utilizadas para predizer eleições?

Claro que sim! Modelos estatísticos sempre têm propriedades preditivas. Um modelo preditivo, no entanto, pode utilizar muito mais informações do que as intenções de voto dos eleitores. 

Alguns exemplos de informações que poderiam ser utilizadas:

- Historicamente, sabemos que indecisos têm uma propensão a votar em candidatos do tipo $A$ do que $B$. Podemos utilizar essa informação para ponderar os não respondentes.
- Historicamente, sabemos que a proporção de brancos e nulos observada nas urnas é diferente do que as pessoas afirmam nas pesquisas. Podemos utilizar esse dado para predizer a proporção de votos brancos e nulos. 
- Em determinadas regiões, as pessoas mudam o voto de última hora, possivelmente por ações ilegais como propaganda em boca de urna. Podemos utilizar essa informação para corrigir os dados levantados via pesquisas eleitorais.
- Podemos utilizar os dados de diversas pesquisas eleitorais ao mesmo tempo, dando pesos diferentes para elas, para predizer os resultados da eleição.

## Como podemos avaliar pesquisas eleitorais?

Pesquisas de intenção de voto só podem ser avaliadas através da metodologia e da execução. Existem diversos parâmetros para levar em conta, como:

- Metodologia de listagem dos indivíduos da amostra: discussões como amostragem probabilística ou amostragem por cotas, por exemplo.
- Metodologia de acesso aos respondentes: discussões como ponto de fluxo, pesquisa em domicílio ou pesquisa por telefone.
- Tratamento da não resposta: discussões sobre auto seleção.
- Verificação das respostas: técnicas para evitar manipulação de resultados e fraudes na coleta de dados.

O problema é que a avaliação das pesquisas sempre acaba sendo subjetiva. Por exemplo, sempre é possível argumentar que uma pesquisa é ruim por não ter utilizado amostragem aleatória simples (AAS) para realização do estudo, o que gera um debate incessante. 

Assim, me parece que a forma mais adequada de avaliar pesquisas de intenção de voto é o atendimento a requisitos formais, como o envio de:

- Base de dados utilizada para realização da pesquisa e script para reprodução dos resultados.
- Descrição detalhada da metodologia.
- Apresentação do questionário do estudo.

O único critério estatístico coerente para avaliar uma pesquisa eleitoral desse tipo seria a comparação dos resultados da pesquisa com outras pesquisas que têm o mesmo objetivo. Por exemplo, se no dia 03 desse mês foram divulgadas dez pesquisas para presidente e uma das pesquisas coloca o candidato $A$ com 15% de vantagem em relação à média das dez pesquisas, existem evidências de que algo pode estar errado nesse levantamento.

Hoje em dia temos alguns agregadores de pesquisas eleitorais que podem ser utilizados para monitorar os resultados das pesquisas e avaliar a qualidade dos resultados. Os meus preferidos são o do [Agregador do JOTA](https://data.jota.info/agregador/), elaborado pelo [Guilherme Jardim Duarte](https://www.linkedin.com/in/guilherme-jardim-duarte-93b82077/?locale=en_US) e o do [Poder360](https://www.poder360.com.br/pesquisas-de-opiniao/), elaborado pelo [Volt Data Lab](https://www.voltdata.info/).

## Como poderíamos mudar essa realidade?

Se o interesse da sociedade está em (2), por quê não divulgar exatamente isso? Nos Estados Unidos, é exatamente isso que o famoso portal [FiveThirtyEight](https://fivethirtyeight.com) se dispôs a fazer. Eles soltam predições periódicas do resultado de eleições e de eventos esportivos. No Brasil, iniciativas como o [PollingData](http://www.pollingdata.com.br) do [Neale El-Dash](https://www.linkedin.com/in/neale/?locale=pt_BR) fazem o mesmo.

Avaliar a qualidade de estudos preditivos para responder (2) também é muito mais fácil. Bastaria comparar o resultado do estudo com os resultados das eleições. O único cuidado seria o de não dar o mesmo peso para pesquisas mais antigas e mais recentes. Uma forma de fazer isso é utilizando a métrica

Minha recomendação é que o TSE defina algumas datas para divulgação de estudos preditivos. Os institutos de pesquisa passariam a divulgar esses estudos nas datas especificadas e, com isso, seria possível elaborar um ranking dos melhores institutos. Essa metodologia já é utilizada pelo BACEN, por exemplo, para [avaliar predições sobre a inflação](https://www4.bcb.gov.br/Pec/GCI/PORT/Focus/top5.asp).

## Wrap-up

- Não avalie pesquisas de intenção de voto a partir de resultados de pesquisas
- Devemos apenas avaliar o atendimento a critérios formais e, no máximo, detectar anomalias a partir da comparação com outras pesquisas.
- Estudos preditivos de resultados de eleições é o que realmente responde ao que a população quer saber.
- Sugiro que o TSE determine algumas datas para divulgação de modelos preditivos e, posteriormente, um ranking dos melhores institutos.

Eu sei que o artigo é polêmico, então por favor sejam gentis nos comentários.

É isso pessoal. Happy Coding ;)


